# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 256
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get -y install mingw-w64 mingw-w64-tools git autotools-dev autoconf automake libtool p7zip
  SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # libusb-1.0
    wget https://github.com/libusb/libusb/releases/download/v1.0.21/libusb-1.0.21.7z
    mkdir libusb1
    cd libusb1
    7zr x ../libusb-1.0.21.7z
    cat >libusb-1.0.pc <<EOF
prefix=$(pwd)
exec_prefix=\\\${prefix}
libdir=\\\${prefix}/MinGW32/dll
includedir=\\\${prefix}/include

Name: libusb-1.0
Description: C API for USB device access from Linux, Mac OS X, Windows and OpenBSD/NetBSD userspace
Version: 1.0.21
Libs: -L\\\${libdir} -lusb-1.0
Cflags: -I\\\${includedir}/libusb-1.0
EOF
    cd ..
    # hidapi
    git clone https://github.com/signal11/hidapi.git
    cd hidapi
    ./bootstrap
    ./configure --prefix=`pwd`/dist/ --host=i686-w64-mingw32
    make -j $(grep -c processor /proc/cpuinfo)
    make install
    cd ..
    # openocd
    wget --trust-server-names https://sourceforge.net/projects/openocd/files/openocd/0.10.0/openocd-0.10.0.tar.bz2/download
    tar xf openocd-0.10.0.tar.bz2
    cd openocd-0.10.0
    export PKG_CONFIG=i686-w64-mingw32-pkg-config \
           PKG_CONFIG_LIBDIR="/home/vagrant/libusb1/" \
           HIDAPI_CFLAGS="-I/home/vagrant/hidapi/dist/include/hidapi" \
           HIDAPI_LIBS="-L/home/vagrant/hidapi/dist/lib -lhidapi"
    ./configure --prefix=`pwd`/dist/ --host=i686-w64-mingw32
    make -j $(grep -c processor /proc/cpuinfo)
    make install
    #
    cp /home/vagrant/hidapi/dist/bin/libhidapi-0.dll dist/bin
    cp /home/vagrant/libusb1/MinGW32/dll/libusb-1.0.dll dist/bin
    tar --transform 's/dist/openocd-0.10.0/' -jcvf openocd-0.10.0-static-i686-mingw32.tar.bz2 dist/
    mv openocd-0.10.0-static-i686-mingw32.tar.bz2 /vagrant/
  SHELL
end
